const Types = {
  GET_SEARCH_RESULTS_REQ: "GET_SEARCH_RESULTS_REQ",
  GET_SEARCH_RESULTS_SUCCESS: "GET_SEARCH_RESULTS_SUCCESS",
  GET_SEARCH_RESULTS_FAIL: "GET_SEARCH_RESULTS_FAIL",
  CLEAR_SEARCH_STORE: "CLEAR_SEARCH_STORE"
};

export default Types;
