const Types = {
  GET_DROPDOWN_OPTION_REQ: "GET_DROPDOWN_OPTION_REQ",
  GET_DROPDOWN_OPTION_SUCCESS: "GET_DROPDOWN_OPTION_SUCCESS",
  GET_DROPDOWN_OPTION_FAIL: "GET_DROPDOWN_OPTION_FAIL",
  CLEAR_HOME_STORE: "CLEAR_HOME_STORE"
};

export default Types;
